06-12 21:50:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "DATASET" already exists; SQL statement:
CREATE TABLE dataset (id bigint primary key auto_increment, element varchar(244)) [42101-170]
06-12 21:50:19 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "DATASET" already exists; SQL statement:
CREATE TABLE dataset (id bigint primary key auto_increment, element varchar(244)) [42101-170]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:634)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:418)
	at clojure.java.jdbc$do_commands$fn__3557.invoke(jdbc.clj:430)
	at clojure.java.jdbc$transaction_STAR_.invoke(jdbc.clj:372)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:429)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:531)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at user$eval3619$fn__3620.invoke(form-init3985820358254883381.clj:6)
	at clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:302)
	at user$eval3619.invoke(form-init3985820358254883381.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
	at clojure.main$repl$fn__7108.invoke(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:258)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__634.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__679$fn__682.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__674.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
org.h2.jdbc.JdbcSQLException: Table "DATASET" already exists; SQL statement:
CREATE TABLE dataset (id bigint primary key auto_increment, element varchar(244)) [42101-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:619)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:418)
	at clojure.java.jdbc$do_commands$fn__3557.invoke(jdbc.clj:430)
	at clojure.java.jdbc$transaction_STAR_.invoke(jdbc.clj:372)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:429)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:531)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at user$eval3619$fn__3620.invoke(form-init3985820358254883381.clj:6)
	at clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:302)
	at user$eval3619.invoke(form-init3985820358254883381.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
	at clojure.main$repl$fn__7108.invoke(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:258)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__634.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__679$fn__682.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__674.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
06-12 22:22:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "DATASET" already exists; SQL statement:
CREATE TABLE dataset (id bigint primary key auto_increment, element varchar(244)) [42101-170]
06-12 22:22:56 jdbc[2]: exception
org.h2.jdbc.JdbcBatchUpdateException: Table "DATASET" already exists; SQL statement:
CREATE TABLE dataset (id bigint primary key auto_increment, element varchar(244)) [42101-170]
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:634)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:418)
	at clojure.java.jdbc$do_commands$fn__3557.invoke(jdbc.clj:430)
	at clojure.java.jdbc$transaction_STAR_.invoke(jdbc.clj:372)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:429)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:531)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at user$eval3757$fn__3758.invoke(form-init8917901946971470429.clj:6)
	at clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:302)
	at user$eval3757.invoke(form-init8917901946971470429.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
	at clojure.main$repl$fn__7108.invoke(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:258)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__634.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__679$fn__682.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__674.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
org.h2.jdbc.JdbcSQLException: Table "DATASET" already exists; SQL statement:
CREATE TABLE dataset (id bigint primary key auto_increment, element varchar(244)) [42101-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:619)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
	at clojure.java.jdbc$execute_batch.invoke(jdbc.clj:418)
	at clojure.java.jdbc$do_commands$fn__3557.invoke(jdbc.clj:430)
	at clojure.java.jdbc$transaction_STAR_.invoke(jdbc.clj:372)
	at clojure.java.jdbc$do_commands.doInvoke(jdbc.clj:429)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.java.jdbc$create_table.doInvoke(jdbc.clj:531)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at user$eval3757$fn__3758.invoke(form-init8917901946971470429.clj:6)
	at clojure.java.jdbc$with_connection_STAR_.invoke(jdbc.clj:302)
	at user$eval3757.invoke(form-init8917901946971470429.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
	at clojure.main$repl$fn__7108.invoke(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:258)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__634.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__679$fn__682.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__674.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
